api_gateway/urls.py
from django.urls import path
from . import views

app_name='api_gateway'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/', views.detail, name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from iils.views import base_views

app_name ='iils'

urlpatterns = [

    path('admin/', admin.site.urls),
    path('iils/', include('iils.urls')),
    path('common/', include('common.urls')),
    path('monitoring/', include('monitoring.urls')),
    path('mapping/', include('mapping.urls')),
    path('report/', include('report.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('api_gateway/', include('api_gateway.urls')),
    path('', base_views.index, name='index'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # static 경로 추가

iils/urls.py
from django.urls import path, include
from .views import base_views, question_views, answer_views

app_name = 'iils'

urlpatterns = [

# base
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    #question
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    #answer
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),

]

monitoring/urls.py
from django.urls import path
from . import views

app_name = 'monitoring'

urlpatterns = [

    path('', views.index, name='index'),
    path('detail/', views.detail, name='detail'),

]

monitoring/models.py
from django.db import models

# Create your models here.

monitoring/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import path
from django.template import loader

from IPython.display import display

from . import views
import pandas as pd
import csv
import os
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
import numpy as np

# Create your views here.

def index(request):
    context = {
    }
    return render(request, 'monitoring/monitoring_list.html', context)



def index_bak(request):
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(
        content_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="somefilename.csv"'},
    )

    # The data is hard-coded here, but you could load it from a database or
    # some other source.
    csv_data = (
        ("First row", "Foo", "Bar", "Baz"),
        ("Second row", "A", "B", "C", '"Testing"', "Here's a quote"),
    )

    t = loader.get_template("my_template_name.txt")
    c = {"data": csv_data}
    response.write(t.render(c))
    context={ response }
    return render(request, context)


def detail(request):
    context = {

    }

    return render(request, 'monitoring/monitoring_detail.html', context)
    #return HttpResponse(" 모니터링 상세 ")

templates/monitoring/monitoring_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center mb-2">
    <div class="col-md-4">
        <div class="card" >
            <img src="/static/images/flower_02.jpg" class="card-img-top" alt="API GATEWAY">
            <div class="card-body">
                <h5 class="card-title"> 모니터링 상세 </h5>
                <p class="card-text"> {{pm10}} </p>
                <a href="{% url 'api_gateway:detail'%}" class="btn btn-primary" class="btn btn-primary">>> 자세히</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/monitoring/monitoring_list.html
{% extends 'base.html' %}
{% block content %}
<h5 class="card-title"> 모니터링 </h5>
<img src="/static/images/sst_compare.png" alt="충전소비율">
<img src="/static/images/ev_st_ratio.png" alt="성장률">

<div class="row justify-content-center mb-2">
    <div class="col-md-4">
        <div class="card" >
            <div class="card-body">
                <a href="{% url 'api_gateway:detail'%}" class="btn btn-primary">>> 자세히</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}