config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from iils.views import base_views

app_name ='iils'

urlpatterns = [

    path('admin/', admin.site.urls),
    path('iils/', include('iils.urls')),
    path('common/', include('common.urls')),
    path('monitoring/', include('monitoring.urls')),
    path('mapping/', include('mapping.urls')),
    path('report/', include('report.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('api_gateway/', include('api_gateway.urls')),
    path('', base_views.index, name='index'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # static 경로 추가

iils/urls.py
from django.urls import path, include
from .views import base_views, question_views, answer_views

app_name = 'iils'

urlpatterns = [

# base
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    #question
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    #answer
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),

]

mapping/urls.py
from django.urls import path
from . import views

app_name='mapping'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/', views.detail, name='detail'),
]

mapping/models.py
from django.db import models

# Create your models here.

mapping/views.py
from django.shortcuts import render
#f=open("static/한국전력공사_지역별 전기차 충전소 현황정보_20231231.csv", 'r', encoding='UTF-8')
f=open("static/경상남도_전기차 충전소 설치현황_20240314.csv", 'r', encoding='cp949')
l=[]
lines = f.readlines()
for line in lines:
    l.append(line.split(','))
    print(line)
    f.close()

    data = l[1:100]

# Create your views here.
def index(request):
    context={'data':data}
    return render(request, 'mapping/mapping_list.html', context)

def detail(request):
    context = {'data': data}
    return render(request, 'mapping/mapping_detail.html', context)

templates/mapping/mapping_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row justify-content-start mb-2">
    <div class="col-md-4">
        <div class="card" >
            <div class="card-body">
                <p></p>
                <h5 class = "text-center"> 공공데이터포탈 지도 연동 </h5><p></p>
                <p class = "text-center"> 지역별 전기차 충전소 현황 </p>
                <p class = "text-center"> 지역명 : 경상남도 </p>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=t7ywec3pik"></script>

<div id="map" style="width:100%;height:100%;"> 공공데이터 지도 </div>

<div> 충전소명  위치 </div>


<script>
    var map = new naver.maps.Map('map', {
        center: new naver.maps.LatLng(35.56514756, 128.1649809),
        //center: new naver.maps.LatLng(37.5666805, 126.9784147),
        zoom: 10

    });
    resize();
        window.addEventListener('resize', resize);


    {% for i in data%}

    var marker = new naver.maps.Marker({
        position: new naver.maps.LatLng({{i.6}},{{i.5}}),
            map: map
        });
    {% endfor%}

    naver.maps.Event.addListener(map, 'click', function(e) {
        marker.setPosition(e.latlng);
        if (infowindow.getMap()) {
                infowindow.close();
        } else {
                infowindow.open(map, marker);
        }
    });

    var contentString = [
        '<div class="iw_inner">',
        '   <h3> 충전소명 : {{i.0}} </h3>',
        '   <p> 주소 : {{i.3}} <br />',
        '   </p>',
        '</div>'
    ].join('');

    // InfoWindow 객체 생성
    var infoWindow = new naver.maps.InfoWindow({
        content: contentString,
        maxWidth: 140,
        backgroundColor: "#eee",
        borderColor: "#2db400",
        borderWidth: 5,
        anchorSize: new naver.maps.Size(30, 30),
        anchorSkew: true,
        anchorColor: "#eee",
        pixelOffset: new naver.maps.Point(20, -20)
    });

   function resize() {
             var mapWidth = window.innerWidth;
             var mapHeight;

          if (mapWidth <= 767) {
              mapWidth = '80vw';
              mapHeight = '200px';
          } else if (mapWidth <= 1023) {
              mapWidth = '700px';
              mapHeight = '400px';
          } else {
              mapWidth = '1000px';
              mapHeight = '600px';
          }

          document.getElementById('map').style.width = mapWidth;
          document.getElementById('map').style.height = mapHeight;
          map.setSize(new naver.maps.Size(parseInt(mapWidth), parseInt(mapHeight)));
      }

   naver.maps.Event.addListener(map, 'mousemove', function(e) {
       var latlng = e.coord;  // 마우스가 위치한 좌표
       // 좌표 정보를 활용하여 HTML 요소에 출력
       document.getElementById('info').innerHTML = '위도: ' + latlng.lat() + ', 경도: ' + latlng.lng();
       searchCoordinateToAddress(latlng);  // 좌표에 대한 주소 정보 검색
   });

   function searchCoordinateToAddress(latlng) {
       naver.maps.Service.reverseGeocode({
               coords: latlng,
               orders: [
                           naver.maps.Service.OrderType.ADDR
               ].join(',')
       }, function(status, response) {
        if (status === naver.maps.Service.Status.ERROR) {
            return alert('Something went wrong!');
        }

        var result = response.v2, // 검색 결과의 컨테이너
            items = result.addresses; // 주소 목록

        if (items.length > 0) {
            // 상세 주소 정보를 HTML 요소에 출력
            document.getElementById('info').innerHTML = '주소: ' + items[0].roadAddress || items[0].jibunAddress;
        }
    });
}

</script>

{% endblock %}

templates/mapping/mapping_detail_241009.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row justify-content-start mb-2">
    <div class="col-md-4">
        <div class="card" >
            <div class="card-body">
                <p></p>
                <h5 class = "text-center"> 공공데이터포탈 지도 연동 </h5><p></p>
                <p class = "text-center"> 지역별 전기차 충전소 현황 </p>
                <p class = "text-center"> 지역명 : 경상남도 </p>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=t7ywec3pik"></script>

<div id="map" style="width:100%;height:100%;"> 공공데이터 지도 </div>

<div> 충전소명  위치 </div>


<script>
    var map = new naver.maps.Map('map', {
        center: new naver.maps.LatLng(35.56514756, 128.1649809),
        zoom: 10
    });

    resize();
        window.addEventListener('resize', resize);

    var jeju = new naver.maps.LatLng(33.3590628, 126.534361),
        busan = new naver.maps.LatLng(35.1797865, 129.0750194),
        dokdo = new naver.maps.LatLngBounds(
                new naver.maps.LatLng(37.2380651, 131.8562652),
                new naver.maps.LatLng(37.2444436, 131.8786475)),
        seoul = new naver.maps.LatLngBounds(
                new naver.maps.LatLng(37.42829747263545, 126.76620435615891),
                new naver.maps.LatLng(37.7010174173061, 127.18379493229875));

   $("#to-jeju").on("click", function(e) {
       e.preventDefault();
       map.setCenter(jeju);
   });
   $("#to-1").on("click", function(e) {
      e.preventDefault();
      map.setZoom(6, true);
   });
   $("#to-dokdo").on("click", function(e) {
       e.preventDefault();
       map.fitBounds(dokdo);
   });
   $("#to-busan").on("click", function(e) {
       e.preventDefault();
       map.panTo(busan);
   });
   $("#to-seoul").on("click", function(e) {
       e.preventDefault();
       map.panToBounds(seoul);
   });
   $("#panBy").on("click", function(e) {
       e.preventDefault();
       map.panBy(new naver.maps.Point(10, 10));
   });

    {% for i in data%}

    var marker = new naver.maps.Marker({
        position: new naver.maps.LatLng({{i.6}},{{i.5}}),
            map: map
        });
    {% endfor%}

    naver.maps.Event.addListener(map, 'click', function(e) {
        marker.setPosition(e.latlng);
        if (infowindow.getMap()) {
                infowindow.close();
        } else {
                infowindow.open(map, marker);
        }
    });

    var contentString = [
        '<div class="iw_inner">',
        '   <h3> 충전소명 : {{i.0}} </h3>',
        '   <p> 주소 : {{i.3}} <br />',
        '   </p>',
        '</div>'
    ].join('');

    // InfoWindow 객체 생성
    var infoWindow = new naver.maps.InfoWindow({
        content: contentString,
        maxWidth: 140,
        backgroundColor: "#eee",
        borderColor: "#2db400",
        borderWidth: 5,
        anchorSize: new naver.maps.Size(30, 30),
        anchorSkew: true,
        anchorColor: "#eee",
        pixelOffset: new naver.maps.Point(20, -20)
    });

   function resize() {
             var mapWidth = window.innerWidth;
             var mapHeight;

          if (mapWidth <= 767) {
              mapWidth = '80vw';
              mapHeight = '200px';
          } else if (mapWidth <= 1023) {
              mapWidth = '700px';
              mapHeight = '400px';
          } else {
              mapWidth = '1000px';
              mapHeight = '600px';
          }

          document.getElementById('map').style.width = mapWidth;
          document.getElementById('map').style.height = mapHeight;
          map.setSize(new naver.maps.Size(parseInt(mapWidth), parseInt(mapHeight)));
      }

   naver.maps.Event.addListener(map, 'mousemove', function(e) {
       var latlng = e.coord;  // 마우스가 위치한 좌표
       // 좌표 정보를 활용하여 HTML 요소에 출력
       document.getElementById('info').innerHTML = '위도: ' + latlng.lat() + ', 경도: ' + latlng.lng();
       searchCoordinateToAddress(latlng);  // 좌표에 대한 주소 정보 검색
   });

   function searchCoordinateToAddress(latlng) {
       naver.maps.Service.reverseGeocode({
               coords: latlng,
               orders: [
                           naver.maps.Service.OrderType.ADDR
               ].join(',')
       }, function(status, response) {
        if (status === naver.maps.Service.Status.ERROR) {
            return alert('Something went wrong!');
        }

        var result = response.v2, // 검색 결과의 컨테이너
            items = result.addresses; // 주소 목록

        if (items.length > 0) {
            // 상세 주소 정보를 HTML 요소에 출력
            document.getElementById('info').innerHTML = '주소: ' + items[0].roadAddress || items[0].jibunAddress;
        }
    });
}

</script>

{% endblock %}

templates/mapping/mapping_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h5 class = "text-center"> 공공데이터포탈 지도 연동 : 전기차 충전소  지역별 현황 </h5>
<p class="card-text"> 지역명 : 경상남도 </p>
<a href="{% url 'mapping:detail'%}" class="btn btn-primary">>> 자세히</a>

<div class="wrap">
    {% for i in data%}
    <div class="container">
        <div class="top">
            <div>충전소명 : {{i.0}}</div>
        </div>
        <div class="bottom">
            <div>경도 : {{i.6}} , 위도 : {{i.5}}</div>
        </div>
    </div>
    {% endfor%}

</div>

{% endblock %}

templates/mapping/mapping_list_241014.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h5 class = "text-center"> 공공데이터포탈 지도 연동 : 전기차 충전소  지역별 현황 </h5>
<p class="card-text"> 지역명 : 경상남도 </p>
<a href="{% url 'mapping:detail'%}" class="btn btn-primary">>> 자세히</a>

<div class="wrap">
    {% for i in data%}
    <div class="container">
        <div class="top">
            <div>충전소명 : {{i.0}}</div>
        </div>
        <div class="bottom">
            <div>경도 : {{i.6}} , 위도 : {{i.5}}</div>
        </div>
    </div>
    {% endfor%}

</div>

{% endblock %}