config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from iils.views import base_views

app_name ='iils'

urlpatterns = [

    path('admin/', admin.site.urls),
    path('iils/', include('iils.urls')),
    path('common/', include('common.urls')),
    path('monitoring/', include('monitoring.urls')),
    path('mapping/', include('mapping.urls')),
    path('report/', include('report.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('api_gateway/', include('api_gateway.urls')),
    path('', base_views.index, name='index'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # static 경로 추가

iils/urls.py
from django.urls import path, include
from .views import base_views, question_views, answer_views

app_name = 'iils'

urlpatterns = [

# base
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    #question
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    #answer
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),

]

iils/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')  # 추천인 추가

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')


class Product(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE) # User는 django.contrib.auth.models가 제공하는 모델
    modify_date = models.DateTimeField(null=True, blank=True)
    pcode = models.CharField(max_length=10)
    pname = models.TextField()
    unitprice = models.IntegerField(default=0)
    discountrate = models.DecimalField(max_digits=11, decimal_places=2,default=0)
    mainfunc = models.CharField(max_length=100, default="")
    imgfile = models.ImageField(null=True, upload_to="", blank=True) # 이미지 컬럼 추가
    detailfunc = models.CharField(max_length=200, default="")

iils/forms.py
from django import forms
from iils.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        #widgets = {
        #    'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #    'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        #}
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

iils/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import QuestionForm, AnswerForm
from .models import Question, Answer
from django.core.paginator import Paginator

from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.

def index(request):
    page = request.GET.get('page', '1')  #페이지
    question_list = Question.objects.order_by('-create_date')
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'iils/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    context = {'question': question}
    return render(request, 'iils/question_detail.html', context)

@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('iils:detail', question_id=question.id)
        else:
            form = AnswerForm()
            context = {'question': question, 'form': form}
        return render(request, 'iils/question_detail.html', context)


@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()
            question.save()
            return redirect('iils:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'iils/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('iils:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('iils:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'iils/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('iils:detail', question_id=question.id)
    question.delete()
    return redirect('iils:index')

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('iils:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('iils:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'iils/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('iils:detail', question_id=answer.question.id)

iils/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer


@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('iils:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'iils/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('iils:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('iils:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'iils/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, ' 삭제 권한이 없습니다. ')
    else:
        answer.delete()
    return redirect('iils:detail', question_id=answer.question.id)


@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('iils:detail', question_id=answer.question.id)

iils/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import Question
from django.core.paginator import Paginator
from django.db.models import Q

# Create your views here.

def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'iils/question_list.html', context)
    #return HttpResponse("통합정보연계시스템 Test Site #1")

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'iils/question_detail.html', context)

iils/views/base_views_241001.py
from django.shortcuts import render, get_object_or_404
from ..models import Question
from django.core.paginator import Paginator

# Create your views here.

def index(request):
    page = request.GET.get('page', '1')  # 페이지
    question_list = Question.objects.order_by('-create_date')
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'iils/question_list.html', context)
    #return HttpResponse("통합정보연계시스템 Test Site #1")

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'iils/question_detail.html', context)


@api_view(('POST',))
def uploadExcelDataToTargetTag(request):
    try:
        # 포스트요청으로 들어온 엑셀파일을 받아온다.
        excel_file = request.FILES['excelFile']

        filename, fileExtension = os.path.splitext(str(excel_file))
        # 파일확장자를 통해 엑셀파일이 맞는지 체크해준다
        if fileExtension != ".xlsx":
            return Response("Unavailable file extension")

        else:
            df = pd.read_excel(excel_file, usecols='C:CU')
            time_array = pd.read_excel(excel_file, usecols='D:CU').columns.to_numpy()

            bulk_list = []

            for row in df.itertuples():
                date = row[1].replace('.', '-')  # timestamp 포멧 변경
                values = row[2:]  # 00:15 ~ 24:00 까지의 values
                timestamp = ""
                for i, d in enumerate(list(values)):
                    if isinstance(d, (int, float)):
                        timestamp = f"{date} {time_array[i]}"

                        bulk_list.append(Data(
                            timestamp=timestamp,
                            value=d
                        ))

            Data.objects.bulk_create(bulk_list, batch_size=250)
            return Response("Data Uploaded")

    except Exception as e:
        print(e)
        return Response('Data Upload Failed')


@api_view(('POST',))
def downloadExcelData(request):
    start_date = request.data['start_date']  # 시작날짜
    end_date = request.data['end_date']  # 끝난 날짜

    datas = Data.objects.filter(timestamp__range=[start_date, end_date])
    columns = ['고객번호', '계기번호', '날짜', '00:00', '00:15', '00:30', '00:45', '01:00', '01:15', '01:30', '01:45', '02:00',
               '02:15', '02:30', '02:45', '03:00', '03:15', '03:30', '03:45', '04:00', '04:15', '04:30', '04:45',
               '05:00', '05:15', '05:30', '05:45', '06:00', '06:15', '06:30', '06:45', '07:00', '07:15', '07:30',
               '07:45', '08:00', '08:15', '08:30', '08:45', '09:00', '09:15', '09:30', '09:45', '10:00', '10:15',
               '10:30', '10:45', '11:00', '11:15', '11:30', '11:45', '11:00', '12:00', '12:15', '12:30', '12:45',
               '13:00', '13:15', '13:30', '13:45', '14:00', '14:15', '14:30', '14:45', '15:00', '15:15', '15:30',
               '15:45', '16:00', '16:15', '16:30', '16:45', '17:00', '17:15', '17:30', '17:45', '18:00', '18:15',
               '18:30', '18:45', '19:00', '19:15', '19:30', '19:45', '20:00', '20:15', '20:30', '20:45', '21:00',
               '21:15', '21:30', '21:45', '22:00', '22:15', '22:30', '22:45', '23:00', '23:15', '23:30', '23:45',
               '합계(kWh)']  # 칼럼 우선 생성해주기,,,노가다,,,ㅎㅎ,,,
    dates = []  # 인스턴스에서 날짜만 저장해주기
    for r in raw_datas:
        date, hour = str(r.timestamp).split(' ')  # 타임스탬프에 날짜와 시간이 모두 있기 때문에 나눠주기
        if date in dates:  # 중복이면 패스
            pass
        else:
            dates.append(date)

    excel_data = [[" " for j in range(len(columns))] for i in range(len(dates))]

    for i in len(dates):
        excel_data[i][2] = dates[i]  # 날짜만 우선 넣어주기

    for data in datas:
        date, hour = str(raw_data.timestamp).split(' ')
        hour = hour[:5]  # 시간만 추출해주기
        for j, column in enumerate(columns): 해당
        시간에
        데이터
        저장해주기
        if hour == column:
            excel_data[dates.index(date)][j] = data.value


result = 0
for x in range(len(excel_data)):
    for y in range(3, len(excel_data[x])):
        if excel_data[x][y] != ' ':
            result += excel_data[x][y]
    excel_data[x][100] = result  # 00:00~23:45분까지 데이터들의 합 저장해주기
df = pd.DataFrame(data, columns=columns)
df.to_excel('sample.xlsx', index=False)
return Response("Data Download")

iils/views/report_views.py
from django.shortcuts import render, get_object_or_404
from openpyxl import Workbook
from io import BytesIO
import pandas as pd

# Create your views here.
wb = Workbook()  # 엑셀 생성
ws = wb.active	# 엑셀 활성화
excelfile = BytesIO() #바이트 배열 생성

ws.title = "제품분류표준" # 엑셀 a1 열 이름 정하기
ws['A1']= '제품명'

wb.save("제품분류표준.xlsx")

wb.close()

templates/iils/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label"> 답 변 내 용 </label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary"> 저 장 하 기 </button>
    </form>
</div>
{% endblock %}

templates/iils/official_report.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
     <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
</div>

{% endblock %}

templates/iils/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
     <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
                {% if product.imgfile %}
                <div class="container border col-10">
                    <div style="width:10%; height:150px; float:left; margin-right:10px;">
                        <img src="{{ product.imgfile.url }}" width="700">
                    </div>
                    {% endif %}
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'iils:question_vote' question.id  %}"
                   class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
                </a>
                {% if request.user == question.author %}
                <a href="{% url 'iils:question_modify' question.id  %}"
                   class="btn btn-sm btn-outline-secondary"> 수 정 </a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'iils:question_delete' question.id  %}"> 삭 제 </a>
            {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}} 개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 test-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'iils:answer_vote' answer.id  %}"
                   class="recommend btn btn-sm btn-outline-secondary"> 추 천
                    <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                </a>
                {% if request.user == answer.author %}
                <a href="{% url 'iils:answer_modify' answer.id  %}"
                   class="btn btn-sm btn-outline-secondary"> 수 정 </a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{% url 'iils:answer_delete' answer.id  %}"> 삭 제 </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'iils:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label"> 답 변 내 용 </label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                      name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value=" 답 변 등 록 " class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
            if(confirm(" 정말로 추천하시겠습니까? ")) {
               location.href = this.dataset.uri;
            };
    });
});
</script>
{% endblock %}

templates/iils/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2"> 질문등록 </h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label"> 제 목 </label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label"> 내 용 </label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>


        <button type="submit" class="btn btn-primary"> 저장하기 </button>
    </form>
    <!--</div>
<div class="container">-->
    <h5 class="my-3 border-bottom pb-2"> 키오스크 등록 </h5>
    <form method="post" class="post-form my-3" enctype="multipart/form-data">
    	<div class="form-group">
            <label for="imgfile"> 제품사진 : </label>
            <input type="file" class="form-control" name="imgfile" id="imgfile">
        </div>
</div>
{% endblock %}

templates/iils/question_list.html
{% extends 'base.html' %}
{% load iils_filter %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'iils:question_create' %}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search"> 찾 기 </button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th> 번  호 </th>
            <th style="width:50%"> 제  목 </th>
            <th> 작 성 자 </th>
            <th> 작 성 일 시 </th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td class="text-center"> <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
            {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                <a href="{% url 'iils:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td class="text-center">{{ question.author.username }}</td>  <!-- 글쓴이 추가 -->
            <td class="text-center">{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4"> 질문이 없습니다. </td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
           href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
             <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
             <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{% url 'iils:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

templates/iils/question_list_bak01.html
<!--{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">-->

<!--{% if question_list %}
    <ul>
    {% for question in question_list %}-->
        <!--<li><a href="/iils/{{ question.id }}/">{{ question.subject }}</a></li>
        <li><a href="{% url 'iils:detail' question.id %}">{{ question.subject }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}-->

{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th> 번  호 </th>
            <th>    제       목     </th>
            <th> 작 성 일 시 </th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td class="text-center" >{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'iils:detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td class="text-center">{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'iils:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}