common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from iils.views import base_views

app_name ='iils'

urlpatterns = [

    path('admin/', admin.site.urls),
    path('iils/', include('iils.urls')),
    path('common/', include('common.urls')),
    path('monitoring/', include('monitoring.urls')),
    path('mapping/', include('mapping.urls')),
    path('report/', include('report.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('api_gateway/', include('api_gateway.urls')),
    path('', base_views.index, name='index'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # static 경로 추가

dashboard/urls.py
from django.urls import path

from . import views

app_name='dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/', views.detail, name='detail'),
]

iils/urls.py
from django.urls import path, include
from .views import base_views, question_views, answer_views

app_name = 'iils'

urlpatterns = [

# base
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    #question
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    #answer
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),

]

mapping/urls.py
from django.urls import path
from . import views

app_name='mapping'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/', views.detail, name='detail'),
]

report/urls.py
from django.urls import path
from . import views

app_name = 'report'

urlpatterns = [

    path('', views.index, name='index'),
    path('detail/', views.detail, name='detail'),

]

iils/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import Question
from django.core.paginator import Paginator
from django.db.models import Q

# Create your views here.

def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'iils/question_list.html', context)
    #return HttpResponse("통합정보연계시스템 Test Site #1")

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'iils/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- iils CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title> 통합정보연계시스템 TEST SITE </title>
</head>
<style>
    @import url(http://fonts.googleapis.com/earlyaccess/notosanskr.css);
    body{
        font-family: 'Noto Sans KR', sans-serif;
    }
    .wrap{
        display: flex;
        justify-content: row;
        gap:16px;
        flex-wrap: wrap;
    }
    .container{
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        flex:21%;
        gap:24px;
        border: 1px solid #EBEAEC;
        box-shadow: 0px 2px 4px rgba(0,0,0,0.3);
        border-radius: 16px;
        padding: 24px;
    }
    .top{
        font-weight:bold;
        font-size:16px;
    }
    .bottom .name{
        font-size:13px;
        color:#727174;
    }
    .botton .date{
        font-size:12px;
        color:#B4B4B6;
    }
</style>
<body>
<br>
    <a class="text-center" href="{% url 'iils:index' %}" >
      <h1 class = "text-center" >통합정보연계시스템 TEST SITE</h1>
    </a>
<br>
    <a class="btn btn-primary" href="#">
        <img src="/static/images/kats_01.jpg" class="card-img-top" alt="HOME">
      <h5 class = "text-center"> 국가기술표준원 </h5>
    </a>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'iils:index' %}"> Home </a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} ( 로그아웃 ) </a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}"> 로그인 </a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}"> 회원가입 </a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'api_gateway:index'%}" class="btn btn-primary"> API연동 </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:index'%}" class="btn btn-primary"> 수출입품목 HSK </a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'monitoring:index'%}" class="btn btn-primary"> 모니터링 </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mapping:index'%}" class="btn btn-primary"> 지도보기 </a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'report:index'%}" class="btn btn-primary"> 보고서 </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        연관기관</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="https://kats.go.kr/main.do" target="_blank">국가기술표준원</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="https://gpck.kr/tree/classification.cs?m=58" target="_blank">제품분류표준코드</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="https://data.go.kr" target="_blank">공공데이터포털</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="https://www.foodsafetykorea.go.kr" target="_blank">식품안전나라</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="https://e-ks.kr" target="_blank">나라인증표준</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="https://www.ksnara.or.kr" target="_blank">KS인증기관협의회</a></li>
                        <li><hr class="dropdown-divider"></li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>
</nav>